language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run heroku-postbuild
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  on:
    branch: master
